# Generated by Django 2.2 on 2021-10-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brightday',
            field=models.DateField(blank=True, null=True, verbose_name='brightday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='social'),
        ),
    ]
